BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[TB_CARGOS] (
    [IdCargo] UNIQUEIDENTIFIER NOT NULL,
    [NomeCargo] NVARCHAR(50) NOT NULL,
    [NivelPermissao] NVARCHAR(20) NOT NULL,
    [DataCad] DATETIME2 NOT NULL CONSTRAINT [TB_CARGOS_DataCad_df] DEFAULT CURRENT_TIMESTAMP,
    [DataMod] DATETIME2 NOT NULL,
    CONSTRAINT [TB_CARGOS_pkey] PRIMARY KEY CLUSTERED ([IdCargo]),
    CONSTRAINT [TB_CARGOS_NomeCargo_key] UNIQUE NONCLUSTERED ([NomeCargo])
);

-- CreateTable
CREATE TABLE [dbo].[TB_FUNCIONARIOS] (
    [IdFuncionario] UNIQUEIDENTIFIER NOT NULL,
    [FK_IdCargo] UNIQUEIDENTIFIER NOT NULL,
    [NomeFuncionario] NVARCHAR(30) NOT NULL,
    [SobrenomeFuncionario] NVARCHAR(200) NOT NULL,
    [Cpf] CHAR(11) NOT NULL,
    [SenhaHash] NVARCHAR(255) NOT NULL,
    [Email] NVARCHAR(255) NOT NULL,
    [CaminhoImagemPerfil] NVARCHAR(255),
    [SituacaoEmpregaticia] NVARCHAR(20) NOT NULL,
    [DataCad] DATETIME2 NOT NULL CONSTRAINT [TB_FUNCIONARIOS_DataCad_df] DEFAULT CURRENT_TIMESTAMP,
    [DataMod] DATETIME2 NOT NULL,
    CONSTRAINT [TB_FUNCIONARIOS_pkey] PRIMARY KEY CLUSTERED ([IdFuncionario]),
    CONSTRAINT [TB_FUNCIONARIOS_Cpf_key] UNIQUE NONCLUSTERED ([Cpf])
);

-- CreateTable
CREATE TABLE [dbo].[TB_TELEFONES] (
    [IdTelefone] UNIQUEIDENTIFIER NOT NULL,
    [FK_IdFuncionario] UNIQUEIDENTIFIER NOT NULL,
    [NumeroTelefone] NVARCHAR(20) NOT NULL,
    [TipoTelefone] NVARCHAR(20) NOT NULL,
    [DataCad] DATETIME2 NOT NULL CONSTRAINT [TB_TELEFONES_DataCad_df] DEFAULT CURRENT_TIMESTAMP,
    [DataMod] DATETIME2 NOT NULL,
    CONSTRAINT [TB_TELEFONES_pkey] PRIMARY KEY CLUSTERED ([IdTelefone])
);

-- CreateTable
CREATE TABLE [dbo].[TB_REGISTRO_ACESSO] (
    [IdAcesso] UNIQUEIDENTIFIER NOT NULL,
    [FK_IdFuncionario] UNIQUEIDENTIFIER NOT NULL,
    [DataHoraAcesso] DATETIME2 NOT NULL,
    [PaginaAcesso] NVARCHAR(100) NOT NULL,
    [DataCad] DATETIME2 NOT NULL CONSTRAINT [TB_REGISTRO_ACESSO_DataCad_df] DEFAULT CURRENT_TIMESTAMP,
    [DataMod] DATETIME2 NOT NULL,
    CONSTRAINT [TB_REGISTRO_ACESSO_pkey] PRIMARY KEY CLUSTERED ([IdAcesso])
);

-- CreateTable
CREATE TABLE [dbo].[TB_OCP] (
    [IdOCP] UNIQUEIDENTIFIER NOT NULL,
    [NomeOCP] NVARCHAR(50) NOT NULL,
    [DataCad] DATETIME2 NOT NULL CONSTRAINT [TB_OCP_DataCad_df] DEFAULT CURRENT_TIMESTAMP,
    [DataMod] DATETIME2 NOT NULL,
    CONSTRAINT [TB_OCP_pkey] PRIMARY KEY CLUSTERED ([IdOCP])
);

-- CreateTable
CREATE TABLE [dbo].[TB_EMPRESAS] (
    [IdEmpresa] UNIQUEIDENTIFIER NOT NULL,
    [NomeEmpresa] NVARCHAR(50) NOT NULL,
    [DataCad] DATETIME2 NOT NULL CONSTRAINT [TB_EMPRESAS_DataCad_df] DEFAULT CURRENT_TIMESTAMP,
    [DataMod] DATETIME2 NOT NULL,
    CONSTRAINT [TB_EMPRESAS_pkey] PRIMARY KEY CLUSTERED ([IdEmpresa])
);

-- CreateTable
CREATE TABLE [dbo].[TB_PROTOCOLO] (
    [IdProtocolo] UNIQUEIDENTIFIER NOT NULL,
    [FK_OCP] UNIQUEIDENTIFIER NOT NULL,
    [FK_Empresa] UNIQUEIDENTIFIER NOT NULL,
    [NomeProtocolo] NVARCHAR(100) NOT NULL,
    [NumeroProtocolo] NVARCHAR(50) NOT NULL,
    [NumeroSEI] NVARCHAR(50) NOT NULL,
    [TipoProtocolo] NVARCHAR(50) NOT NULL,
    [DiaAbertura] DATE NOT NULL,
    [DiaEntrega] DATE,
    [DataCad] DATETIME2 NOT NULL CONSTRAINT [TB_PROTOCOLO_DataCad_df] DEFAULT CURRENT_TIMESTAMP,
    [DataMod] DATETIME2 NOT NULL,
    CONSTRAINT [TB_PROTOCOLO_pkey] PRIMARY KEY CLUSTERED ([IdProtocolo]),
    CONSTRAINT [TB_PROTOCOLO_NumeroProtocolo_key] UNIQUE NONCLUSTERED ([NumeroProtocolo]),
    CONSTRAINT [TB_PROTOCOLO_NumeroSEI_key] UNIQUE NONCLUSTERED ([NumeroSEI])
);

-- CreateTable
CREATE TABLE [dbo].[TB_AMOSTRAS] (
    [IdAmostra] UNIQUEIDENTIFIER NOT NULL,
    [FK_IdProtocolo] UNIQUEIDENTIFIER NOT NULL,
    [CodigoAmostra] NVARCHAR(100) NOT NULL,
    [NomeAmostra] NVARCHAR(100) NOT NULL,
    [SituacaoAmostra] NVARCHAR(50) NOT NULL,
    [ClassificacaoAmostra] NVARCHAR(50) NOT NULL,
    [SubclassificacaoAmostra] NVARCHAR(50) NOT NULL,
    [Descricao] NVARCHAR(1000),
    [DataCad] DATETIME2 NOT NULL CONSTRAINT [TB_AMOSTRAS_DataCad_df] DEFAULT CURRENT_TIMESTAMP,
    [DataMod] DATETIME2 NOT NULL,
    CONSTRAINT [TB_AMOSTRAS_pkey] PRIMARY KEY CLUSTERED ([IdAmostra])
);

-- CreateTable
CREATE TABLE [dbo].[TB_ENSAIOS] (
    [IdEnsaio] UNIQUEIDENTIFIER NOT NULL,
    [FK_IdProtocolo] UNIQUEIDENTIFIER NOT NULL,
    [FK_IdTipoEnsaio] UNIQUEIDENTIFIER NOT NULL,
    [FK_IdFuncionario] UNIQUEIDENTIFIER NOT NULL,
    [PapelEnsaio] NVARCHAR(50) NOT NULL,
    [DataCad] DATETIME2 NOT NULL CONSTRAINT [TB_ENSAIOS_DataCad_df] DEFAULT CURRENT_TIMESTAMP,
    [DataMod] DATETIME2 NOT NULL,
    CONSTRAINT [TB_ENSAIOS_pkey] PRIMARY KEY CLUSTERED ([IdEnsaio])
);

-- CreateTable
CREATE TABLE [dbo].[TB_AMOSTRA_ENSAIO] (
    [IdAmostraEnsaio] UNIQUEIDENTIFIER NOT NULL,
    [FK_IdAmostra] UNIQUEIDENTIFIER NOT NULL,
    [FK_IdEnsaio] UNIQUEIDENTIFIER NOT NULL,
    [FK_IdInstrumento] UNIQUEIDENTIFIER NOT NULL,
    [FK_IdFuncionario] UNIQUEIDENTIFIER NOT NULL,
    [DataHoraRealizacao] DATETIME2 NOT NULL,
    [Temperatura] DECIMAL(10,2) NOT NULL,
    [Umidade] DECIMAL(10,2) NOT NULL,
    [Pressao] DECIMAL(10,2) NOT NULL,
    [DataCad] DATETIME2 NOT NULL CONSTRAINT [TB_AMOSTRA_ENSAIO_DataCad_df] DEFAULT CURRENT_TIMESTAMP,
    [DataMod] DATETIME2 NOT NULL,
    CONSTRAINT [TB_AMOSTRA_ENSAIO_pkey] PRIMARY KEY CLUSTERED ([IdAmostraEnsaio])
);

-- CreateTable
CREATE TABLE [dbo].[TB_DADOS_ENSAIO] (
    [IdDadosEnsaio] UNIQUEIDENTIFIER NOT NULL,
    [FK_IdAmostraEnsaio] UNIQUEIDENTIFIER NOT NULL,
    [FK_IdCampoEnsaio] UNIQUEIDENTIFIER NOT NULL,
    [Dado] NVARCHAR(max) NOT NULL,
    [DataCad] DATETIME2 NOT NULL CONSTRAINT [TB_DADOS_ENSAIO_DataCad_df] DEFAULT CURRENT_TIMESTAMP,
    [DataMod] DATETIME2 NOT NULL,
    CONSTRAINT [TB_DADOS_ENSAIO_pkey] PRIMARY KEY CLUSTERED ([IdDadosEnsaio])
);

-- CreateTable
CREATE TABLE [dbo].[TB_TIPO_ENSAIO] (
    [IdTipoEnsaio] UNIQUEIDENTIFIER NOT NULL,
    [NomeEnsaio] NVARCHAR(100) NOT NULL,
    [CategoriaAplicavel] NVARCHAR(50) NOT NULL,
    [DataCad] DATETIME2 NOT NULL CONSTRAINT [TB_TIPO_ENSAIO_DataCad_df] DEFAULT CURRENT_TIMESTAMP,
    [DataMod] DATETIME2 NOT NULL,
    CONSTRAINT [TB_TIPO_ENSAIO_pkey] PRIMARY KEY CLUSTERED ([IdTipoEnsaio])
);

-- CreateTable
CREATE TABLE [dbo].[TB_CAMPO_ENSAIO] (
    [IdCampoEnsaio] UNIQUEIDENTIFIER NOT NULL,
    [FK_IdTipoEnsaio] UNIQUEIDENTIFIER NOT NULL,
    [NomeCampo] NVARCHAR(100) NOT NULL,
    [Obrigatoriedade] BIT NOT NULL,
    [UnidadeMedida] NVARCHAR(20) NOT NULL,
    [TipoDado] NVARCHAR(50) NOT NULL,
    [DataCad] DATETIME2 NOT NULL CONSTRAINT [TB_CAMPO_ENSAIO_DataCad_df] DEFAULT CURRENT_TIMESTAMP,
    [DataMod] DATETIME2 NOT NULL,
    CONSTRAINT [TB_CAMPO_ENSAIO_pkey] PRIMARY KEY CLUSTERED ([IdCampoEnsaio])
);

-- CreateTable
CREATE TABLE [dbo].[TB_FUNCIONARIOS_ENSAIO] (
    [IdFuncionarioEnsaio] UNIQUEIDENTIFIER NOT NULL,
    [FK_IdFuncionario] UNIQUEIDENTIFIER NOT NULL,
    [FK_IdEnsaio] UNIQUEIDENTIFIER NOT NULL,
    [DataCad] DATETIME2 NOT NULL CONSTRAINT [TB_FUNCIONARIOS_ENSAIO_DataCad_df] DEFAULT CURRENT_TIMESTAMP,
    [DataMod] DATETIME2 NOT NULL,
    CONSTRAINT [TB_FUNCIONARIOS_ENSAIO_pkey] PRIMARY KEY CLUSTERED ([IdFuncionarioEnsaio])
);

-- CreateTable
CREATE TABLE [dbo].[TB_INSTRUMENTO] (
    [IdInstrumento] UNIQUEIDENTIFIER NOT NULL,
    [NomeInstrumento] NVARCHAR(100) NOT NULL,
    [UltimaCalibracao] DATE NOT NULL,
    [DataCad] DATETIME2 NOT NULL CONSTRAINT [TB_INSTRUMENTO_DataCad_df] DEFAULT CURRENT_TIMESTAMP,
    [DataMod] DATETIME2 NOT NULL,
    CONSTRAINT [TB_INSTRUMENTO_pkey] PRIMARY KEY CLUSTERED ([IdInstrumento])
);

-- AddForeignKey
ALTER TABLE [dbo].[TB_FUNCIONARIOS] ADD CONSTRAINT [TB_FUNCIONARIOS_FK_IdCargo_fkey] FOREIGN KEY ([FK_IdCargo]) REFERENCES [dbo].[TB_CARGOS]([IdCargo]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[TB_TELEFONES] ADD CONSTRAINT [TB_TELEFONES_FK_IdFuncionario_fkey] FOREIGN KEY ([FK_IdFuncionario]) REFERENCES [dbo].[TB_FUNCIONARIOS]([IdFuncionario]) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[TB_REGISTRO_ACESSO] ADD CONSTRAINT [TB_REGISTRO_ACESSO_FK_IdFuncionario_fkey] FOREIGN KEY ([FK_IdFuncionario]) REFERENCES [dbo].[TB_FUNCIONARIOS]([IdFuncionario]) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[TB_PROTOCOLO] ADD CONSTRAINT [TB_PROTOCOLO_FK_OCP_fkey] FOREIGN KEY ([FK_OCP]) REFERENCES [dbo].[TB_OCP]([IdOCP]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[TB_PROTOCOLO] ADD CONSTRAINT [TB_PROTOCOLO_FK_Empresa_fkey] FOREIGN KEY ([FK_Empresa]) REFERENCES [dbo].[TB_EMPRESAS]([IdEmpresa]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[TB_AMOSTRAS] ADD CONSTRAINT [TB_AMOSTRAS_FK_IdProtocolo_fkey] FOREIGN KEY ([FK_IdProtocolo]) REFERENCES [dbo].[TB_PROTOCOLO]([IdProtocolo]) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[TB_ENSAIOS] ADD CONSTRAINT [TB_ENSAIOS_FK_IdProtocolo_fkey] FOREIGN KEY ([FK_IdProtocolo]) REFERENCES [dbo].[TB_PROTOCOLO]([IdProtocolo]) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[TB_ENSAIOS] ADD CONSTRAINT [TB_ENSAIOS_FK_IdTipoEnsaio_fkey] FOREIGN KEY ([FK_IdTipoEnsaio]) REFERENCES [dbo].[TB_TIPO_ENSAIO]([IdTipoEnsaio]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[TB_ENSAIOS] ADD CONSTRAINT [TB_ENSAIOS_FK_IdFuncionario_fkey] FOREIGN KEY ([FK_IdFuncionario]) REFERENCES [dbo].[TB_FUNCIONARIOS]([IdFuncionario]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[TB_AMOSTRA_ENSAIO] ADD CONSTRAINT [TB_AMOSTRA_ENSAIO_FK_IdAmostra_fkey] FOREIGN KEY ([FK_IdAmostra]) REFERENCES [dbo].[TB_AMOSTRAS]([IdAmostra]) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[TB_AMOSTRA_ENSAIO] ADD CONSTRAINT [TB_AMOSTRA_ENSAIO_FK_IdEnsaio_fkey] FOREIGN KEY ([FK_IdEnsaio]) REFERENCES [dbo].[TB_ENSAIOS]([IdEnsaio]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[TB_AMOSTRA_ENSAIO] ADD CONSTRAINT [TB_AMOSTRA_ENSAIO_FK_IdInstrumento_fkey] FOREIGN KEY ([FK_IdInstrumento]) REFERENCES [dbo].[TB_INSTRUMENTO]([IdInstrumento]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[TB_AMOSTRA_ENSAIO] ADD CONSTRAINT [TB_AMOSTRA_ENSAIO_FK_IdFuncionario_fkey] FOREIGN KEY ([FK_IdFuncionario]) REFERENCES [dbo].[TB_FUNCIONARIOS]([IdFuncionario]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[TB_DADOS_ENSAIO] ADD CONSTRAINT [TB_DADOS_ENSAIO_FK_IdAmostraEnsaio_fkey] FOREIGN KEY ([FK_IdAmostraEnsaio]) REFERENCES [dbo].[TB_AMOSTRA_ENSAIO]([IdAmostraEnsaio]) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[TB_DADOS_ENSAIO] ADD CONSTRAINT [TB_DADOS_ENSAIO_FK_IdCampoEnsaio_fkey] FOREIGN KEY ([FK_IdCampoEnsaio]) REFERENCES [dbo].[TB_CAMPO_ENSAIO]([IdCampoEnsaio]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[TB_CAMPO_ENSAIO] ADD CONSTRAINT [TB_CAMPO_ENSAIO_FK_IdTipoEnsaio_fkey] FOREIGN KEY ([FK_IdTipoEnsaio]) REFERENCES [dbo].[TB_TIPO_ENSAIO]([IdTipoEnsaio]) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[TB_FUNCIONARIOS_ENSAIO] ADD CONSTRAINT [TB_FUNCIONARIOS_ENSAIO_FK_IdFuncionario_fkey] FOREIGN KEY ([FK_IdFuncionario]) REFERENCES [dbo].[TB_FUNCIONARIOS]([IdFuncionario]) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[TB_FUNCIONARIOS_ENSAIO] ADD CONSTRAINT [TB_FUNCIONARIOS_ENSAIO_FK_IdEnsaio_fkey] FOREIGN KEY ([FK_IdEnsaio]) REFERENCES [dbo].[TB_ENSAIOS]([IdEnsaio]) ON DELETE CASCADE ON UPDATE CASCADE;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
